platform :ios, '9.0'

source 'https://gitlab.rambler.ru/cocoapods/cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'GoVision' do
    # Model & Network
    pod 'AFNetworking', '2.6.3'
    pod 'AFNetworkActivityLogger', '2.0.4'
    
    # UI
    pod 'PEPhotoCropEditor', '1.3.1'
    
    # Helpers
    pod 'ViperMcFlurry', '1.5.2'
    pod 'Typhoon', '3.3.4'
    pod 'RamblerTyphoonUtils/AssemblyCollector', '1.5.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Nimbus'
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
            end
        end
    end
end
